import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from '../components/navbar'
import Header from '../components/header'
import { getProjects, getSocials } from './api/api'

export default function Home({
  projects,
  socials
}: {
  projects: any
  socials: any
}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="app-container bg-cultured">
        <Header socials={socials} />
        <NavBar />
      </div>
    </>
  )
}

export async function getServerSideProps() {
  const projects = (await getProjects()) || []
  const socials = (await getSocials()) || []
  console.log('socials')
  console.log(socials)
  console.log('Projects')
  console.log(projects)
  return {
    props: { projects, socials }
  }
}
